/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_Test */

#ifndef _Included_com_test_Test
#define _Included_com_test_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_Test
 * Method:    hi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_test_Test_hi
  (JNIEnv *, jobject);

/*
 * Class:     com_test_Test
 * Method:    dummyTask
 * Signature: ()Lcom/task/Task;
 */
JNIEXPORT jobject JNICALL Java_com_test_Test_dummyTask
  (JNIEnv *, jobject);

/*
 * Class:     com_test_Test
 * Method:    dummyTasks
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_test_Test_dummyTasks
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
